name: Build SFA PuerNya

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4.1.1
        with:
          path: sing-box
          repository: PuerNya/sing-box
          ref: building
          fetch-depth: 0

      - name: Checkout app repository
        uses: actions/checkout@v4.1.1
        with:
          path: sfa
          repository: LQ2002/sing-box-for-android
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: stable

      - name: Setup Java and Android SDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b

      - name: Get sing-box version
        id: sing-box
        run: |
          cd sing-box
          git remote add sekai https://github.com/SagerNet/sing-box
          git fetch --tags sekai
          echo "version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)" >> $GITHUB_OUTPUT

      - name: Build libbox
        env:
          CC: ${{steps.setup-ndk.outputs.ndk-path}}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang
          TAGS: with_quic,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_clash_api,with_gvisor
          VERSION: ${{steps.sing-box.outputs.version}}
        run: |
          cd sing-box
          make lib_install
          gomobile bind -v -a -trimpath -androidapi 21 -javapkg=io.nekohasekai -libname=box -tags ${TAGS} -ldflags "-X github.com/sagernet/sing-box/constant.Version=${VERSION} -s -w -buildid=" ./experimental/libbox

      - name: Build app
        env:
          VERSION: ${{steps.sing-box.outputs.version}}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cp ./sing-box/libbox.aar sfa/app/libs/
          cd sfa
          echo "VERSION_NAME=${VERSION}" > local.properties
          echo "VERSION_CODE=$(date +%Y%m%d%H)" >> local.properties
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$PWD/app/release.keystore \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: Upload APKs
        uses: actions/upload-artifact@v4.1.0
        env:
          version: ${{steps.sing-box.outputs.version}}
        with:
          name: SFA-PuerNya-${{env.version}}
          path: sfa/app/build/outputs/apk/**/*.apk
          compression-level: 9

      - name: Create GitHub Release and upload APKs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{steps.sing-box.outputs.version}}
        run: |
          gh release create v${VERSION} --title "Release v${VERSION}" --notes "Automated release of version ${VERSION}" \
            sfa/app/build/outputs/apk/other/release/*.apk
